### ISSUE TITLE
I tried to use the pre-trained face model for hair color editing process,Is this normal?

### ISSUE THREAD

**Issue by 123456klk1** [Yueming6568/DeltaEdit#6]
Hi, I am playing with your DeltaEdit project and when I try to diversify the edit hair color it does not work, this is the result of my run of editing the pink color.
origin：
![0001--face with pink hair-origin](https://github.com/Yueming6568/DeltaEdit/assets/53042912/f8faaaf8-8957-406f-bc18-ec3529db922d)

result：
![0001--face with pink hair-result](https://github.com/Yueming6568/DeltaEdit/assets/53042912/4b7a473a-7be0-4955-999c-2a980f234e8d)

**Comment by 123456klk1** [comment]
I think it may be that the StyleGAN generated images are not large enough for the dataset, resulting in some variations not being learned, yes?

**Comment by Yueming6568** [comment]
> I think it may be that the StyleGAN generated images are not large enough for the dataset, resulting in some variations not being learned, yes?

exactly

**Comment by Yueming6568** [comment]
solved!

**Comment by 123456klk1** [comment]
Thank you so much for open source.

**Comment by 123456klk1** [comment]
Thanks.
